package com.sgs.model.view;

import com.sgs.model.entity.SgsCreateCreditMemosTImpl;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 17 23:58:08 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SgsCreateCreditMemosTVORowImpl extends ViewRowImpl {
    public static final int ENTITY_SGSCREATECREDITMEMOST = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CreditMemosId,
        CreditDate,
        AllocationId,
        FromBu,
        FromOu,
        FromDeptId,
        FromJobCode,
        ToBu,
        ToOu,
        ToDeptId,
        ToJobCode,
        OffsetGlAccountCr,
        ToGlAccountDr,
        TransactionCurrency,
        Amount,
        GstVatRate,
        GstVatAmount,
        InvoiceAmount,
        ReversalAmount,
        RevsersalGstVatAmount,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CREDITMEMOSID = AttributesEnum.CreditMemosId.index();
    public static final int CREDITDATE = AttributesEnum.CreditDate.index();
    public static final int ALLOCATIONID = AttributesEnum.AllocationId.index();
    public static final int FROMBU = AttributesEnum.FromBu.index();
    public static final int FROMOU = AttributesEnum.FromOu.index();
    public static final int FROMDEPTID = AttributesEnum.FromDeptId.index();
    public static final int FROMJOBCODE = AttributesEnum.FromJobCode.index();
    public static final int TOBU = AttributesEnum.ToBu.index();
    public static final int TOOU = AttributesEnum.ToOu.index();
    public static final int TODEPTID = AttributesEnum.ToDeptId.index();
    public static final int TOJOBCODE = AttributesEnum.ToJobCode.index();
    public static final int OFFSETGLACCOUNTCR = AttributesEnum.OffsetGlAccountCr.index();
    public static final int TOGLACCOUNTDR = AttributesEnum.ToGlAccountDr.index();
    public static final int TRANSACTIONCURRENCY = AttributesEnum.TransactionCurrency.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int GSTVATRATE = AttributesEnum.GstVatRate.index();
    public static final int GSTVATAMOUNT = AttributesEnum.GstVatAmount.index();
    public static final int INVOICEAMOUNT = AttributesEnum.InvoiceAmount.index();
    public static final int REVERSALAMOUNT = AttributesEnum.ReversalAmount.index();
    public static final int REVSERSALGSTVATAMOUNT = AttributesEnum.RevsersalGstVatAmount.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SgsCreateCreditMemosTVORowImpl() {
    }

    /**
     * Gets SgsCreateCreditMemosT entity object.
     * @return the SgsCreateCreditMemosT
     */
    public SgsCreateCreditMemosTImpl getSgsCreateCreditMemosT() {
        return (SgsCreateCreditMemosTImpl) getEntity(ENTITY_SGSCREATECREDITMEMOST);
    }

    /**
     * Gets the attribute value for CREDIT_MEMOS_ID using the alias name CreditMemosId.
     * @return the CREDIT_MEMOS_ID
     */
    public Integer getCreditMemosId() {
        return (Integer) getAttributeInternal(CREDITMEMOSID);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_MEMOS_ID using the alias name CreditMemosId.
     * @param value value to set the CREDIT_MEMOS_ID
     */
    public void setCreditMemosId(Integer value) {
        setAttributeInternal(CREDITMEMOSID, value);
    }

    /**
     * Gets the attribute value for CREDIT_DATE using the alias name CreditDate.
     * @return the CREDIT_DATE
     */
    public Date getCreditDate() {
        return (Date) getAttributeInternal(CREDITDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREDIT_DATE using the alias name CreditDate.
     * @param value value to set the CREDIT_DATE
     */
    public void setCreditDate(Date value) {
        setAttributeInternal(CREDITDATE, value);
    }

    /**
     * Gets the attribute value for ALLOCATION_ID using the alias name AllocationId.
     * @return the ALLOCATION_ID
     */
    public String getAllocationId() {
        return (String) getAttributeInternal(ALLOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOCATION_ID using the alias name AllocationId.
     * @param value value to set the ALLOCATION_ID
     */
    public void setAllocationId(String value) {
        setAttributeInternal(ALLOCATIONID, value);
    }

    /**
     * Gets the attribute value for FROM_BU using the alias name FromBu.
     * @return the FROM_BU
     */
    public String getFromBu() {
        return (String) getAttributeInternal(FROMBU);
    }

    /**
     * Sets <code>value</code> as attribute value for FROM_BU using the alias name FromBu.
     * @param value value to set the FROM_BU
     */
    public void setFromBu(String value) {
        setAttributeInternal(FROMBU, value);
    }

    /**
     * Gets the attribute value for FROM_OU using the alias name FromOu.
     * @return the FROM_OU
     */
    public String getFromOu() {
        return (String) getAttributeInternal(FROMOU);
    }

    /**
     * Sets <code>value</code> as attribute value for FROM_OU using the alias name FromOu.
     * @param value value to set the FROM_OU
     */
    public void setFromOu(String value) {
        setAttributeInternal(FROMOU, value);
    }

    /**
     * Gets the attribute value for FROM_DEPT_ID using the alias name FromDeptId.
     * @return the FROM_DEPT_ID
     */
    public String getFromDeptId() {
        return (String) getAttributeInternal(FROMDEPTID);
    }

    /**
     * Sets <code>value</code> as attribute value for FROM_DEPT_ID using the alias name FromDeptId.
     * @param value value to set the FROM_DEPT_ID
     */
    public void setFromDeptId(String value) {
        setAttributeInternal(FROMDEPTID, value);
    }

    /**
     * Gets the attribute value for FROM_JOB_CODE using the alias name FromJobCode.
     * @return the FROM_JOB_CODE
     */
    public String getFromJobCode() {
        return (String) getAttributeInternal(FROMJOBCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for FROM_JOB_CODE using the alias name FromJobCode.
     * @param value value to set the FROM_JOB_CODE
     */
    public void setFromJobCode(String value) {
        setAttributeInternal(FROMJOBCODE, value);
    }

    /**
     * Gets the attribute value for TO_BU using the alias name ToBu.
     * @return the TO_BU
     */
    public String getToBu() {
        return (String) getAttributeInternal(TOBU);
    }

    /**
     * Sets <code>value</code> as attribute value for TO_BU using the alias name ToBu.
     * @param value value to set the TO_BU
     */
    public void setToBu(String value) {
        setAttributeInternal(TOBU, value);
    }

    /**
     * Gets the attribute value for TO_OU using the alias name ToOu.
     * @return the TO_OU
     */
    public String getToOu() {
        return (String) getAttributeInternal(TOOU);
    }

    /**
     * Sets <code>value</code> as attribute value for TO_OU using the alias name ToOu.
     * @param value value to set the TO_OU
     */
    public void setToOu(String value) {
        setAttributeInternal(TOOU, value);
    }

    /**
     * Gets the attribute value for TO_DEPT_ID using the alias name ToDeptId.
     * @return the TO_DEPT_ID
     */
    public String getToDeptId() {
        return (String) getAttributeInternal(TODEPTID);
    }

    /**
     * Sets <code>value</code> as attribute value for TO_DEPT_ID using the alias name ToDeptId.
     * @param value value to set the TO_DEPT_ID
     */
    public void setToDeptId(String value) {
        setAttributeInternal(TODEPTID, value);
    }

    /**
     * Gets the attribute value for TO_JOB_CODE using the alias name ToJobCode.
     * @return the TO_JOB_CODE
     */
    public String getToJobCode() {
        return (String) getAttributeInternal(TOJOBCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TO_JOB_CODE using the alias name ToJobCode.
     * @param value value to set the TO_JOB_CODE
     */
    public void setToJobCode(String value) {
        setAttributeInternal(TOJOBCODE, value);
    }

    /**
     * Gets the attribute value for OFFSET_GL_ACCOUNT_CR using the alias name OffsetGlAccountCr.
     * @return the OFFSET_GL_ACCOUNT_CR
     */
    public String getOffsetGlAccountCr() {
        return (String) getAttributeInternal(OFFSETGLACCOUNTCR);
    }

    /**
     * Sets <code>value</code> as attribute value for OFFSET_GL_ACCOUNT_CR using the alias name OffsetGlAccountCr.
     * @param value value to set the OFFSET_GL_ACCOUNT_CR
     */
    public void setOffsetGlAccountCr(String value) {
        setAttributeInternal(OFFSETGLACCOUNTCR, value);
    }

    /**
     * Gets the attribute value for TO_GL_ACCOUNT_DR using the alias name ToGlAccountDr.
     * @return the TO_GL_ACCOUNT_DR
     */
    public String getToGlAccountDr() {
        return (String) getAttributeInternal(TOGLACCOUNTDR);
    }

    /**
     * Sets <code>value</code> as attribute value for TO_GL_ACCOUNT_DR using the alias name ToGlAccountDr.
     * @param value value to set the TO_GL_ACCOUNT_DR
     */
    public void setToGlAccountDr(String value) {
        setAttributeInternal(TOGLACCOUNTDR, value);
    }

    /**
     * Gets the attribute value for TRANSACTION_CURRENCY using the alias name TransactionCurrency.
     * @return the TRANSACTION_CURRENCY
     */
    public String getTransactionCurrency() {
        return (String) getAttributeInternal(TRANSACTIONCURRENCY);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSACTION_CURRENCY using the alias name TransactionCurrency.
     * @param value value to set the TRANSACTION_CURRENCY
     */
    public void setTransactionCurrency(String value) {
        setAttributeInternal(TRANSACTIONCURRENCY, value);
    }

    /**
     * Gets the attribute value for AMOUNT using the alias name Amount.
     * @return the AMOUNT
     */
    public BigDecimal getAmount() {
        return (BigDecimal) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for AMOUNT using the alias name Amount.
     * @param value value to set the AMOUNT
     */
    public void setAmount(BigDecimal value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for GST_VAT_RATE using the alias name GstVatRate.
     * @return the GST_VAT_RATE
     */
    public String getGstVatRate() {
        return (String) getAttributeInternal(GSTVATRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GST_VAT_RATE using the alias name GstVatRate.
     * @param value value to set the GST_VAT_RATE
     */
    public void setGstVatRate(String value) {
        setAttributeInternal(GSTVATRATE, value);
    }

    /**
     * Gets the attribute value for GST_VAT_AMOUNT using the alias name GstVatAmount.
     * @return the GST_VAT_AMOUNT
     */
    public BigDecimal getGstVatAmount() {
        return (BigDecimal) getAttributeInternal(GSTVATAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for GST_VAT_AMOUNT using the alias name GstVatAmount.
     * @param value value to set the GST_VAT_AMOUNT
     */
    public void setGstVatAmount(BigDecimal value) {
        setAttributeInternal(GSTVATAMOUNT, value);
    }

    /**
     * Gets the attribute value for INVOICE_AMOUNT using the alias name InvoiceAmount.
     * @return the INVOICE_AMOUNT
     */
    public BigDecimal getInvoiceAmount() {
        return (BigDecimal) getAttributeInternal(INVOICEAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_AMOUNT using the alias name InvoiceAmount.
     * @param value value to set the INVOICE_AMOUNT
     */
    public void setInvoiceAmount(BigDecimal value) {
        setAttributeInternal(INVOICEAMOUNT, value);
    }

    /**
     * Gets the attribute value for REVERSAL_AMOUNT using the alias name ReversalAmount.
     * @return the REVERSAL_AMOUNT
     */
    public BigDecimal getReversalAmount() {
        return (BigDecimal) getAttributeInternal(REVERSALAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for REVERSAL_AMOUNT using the alias name ReversalAmount.
     * @param value value to set the REVERSAL_AMOUNT
     */
    public void setReversalAmount(BigDecimal value) {
        setAttributeInternal(REVERSALAMOUNT, value);
    }

    /**
     * Gets the attribute value for REVSERSAL_GST_VAT_AMOUNT using the alias name RevsersalGstVatAmount.
     * @return the REVSERSAL_GST_VAT_AMOUNT
     */
    public BigDecimal getRevsersalGstVatAmount() {
        return (BigDecimal) getAttributeInternal(REVSERSALGSTVATAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for REVSERSAL_GST_VAT_AMOUNT using the alias name RevsersalGstVatAmount.
     * @param value value to set the REVSERSAL_GST_VAT_AMOUNT
     */
    public void setRevsersalGstVatAmount(BigDecimal value) {
        setAttributeInternal(REVSERSALGSTVATAMOUNT, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UPDATED_DATE using the alias name UpdatedDate.
     * @return the UPDATED_DATE
     */
    public Date getUpdatedDate() {
        return (Date) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_DATE using the alias name UpdatedDate.
     * @param value value to set the UPDATED_DATE
     */
    public void setUpdatedDate(Date value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @return the UPDATED_BY
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @param value value to set the UPDATED_BY
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }
}

