package com.sgs.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 21 22:31:41 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SgsIsdInvoiceNoLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SgsIsdInvoiceNoLOVImpl() {
    }
}

