package com.sgs.model.view;

import com.sgs.model.entity.SgsIcoDocAttachmentsImpl;

import java.sql.Date;

import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 16 15:32:04 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SgsIcoDocAttachmentsViewVORowImpl extends ViewRowImpl {


    public static final int ENTITY_SGSICODOCATTACHMENTS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        SupportingDocTypeId,
        SupportingDocTypeValue,
        Attachment,
        UploadDate,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy,
        UploadedBy,
        IcoDocAttachments;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SUPPORTINGDOCTYPEID = AttributesEnum.SupportingDocTypeId.index();
    public static final int SUPPORTINGDOCTYPEVALUE = AttributesEnum.SupportingDocTypeValue.index();
    public static final int ATTACHMENT = AttributesEnum.Attachment.index();
    public static final int UPLOADDATE = AttributesEnum.UploadDate.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPLOADEDBY = AttributesEnum.UploadedBy.index();
    public static final int ICODOCATTACHMENTS = AttributesEnum.IcoDocAttachments.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SgsIcoDocAttachmentsViewVORowImpl() {
    }

    /**
     * Gets SgsIcoDocAttachments entity object.
     * @return the SgsIcoDocAttachments
     */
    public SgsIcoDocAttachmentsImpl getSgsIcoDocAttachments() {
        return (SgsIcoDocAttachmentsImpl) getEntity(ENTITY_SGSICODOCATTACHMENTS);
    }

    /**
     * Gets the attribute value for SUPPORTING_DOC_TYPE_ID using the alias name SupportingDocTypeId.
     * @return the SUPPORTING_DOC_TYPE_ID
     */
    public Integer getSupportingDocTypeId() {
        return (Integer) getAttributeInternal(SUPPORTINGDOCTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPPORTING_DOC_TYPE_ID using the alias name SupportingDocTypeId.
     * @param value value to set the SUPPORTING_DOC_TYPE_ID
     */
    public void setSupportingDocTypeId(Integer value) {
        setAttributeInternal(SUPPORTINGDOCTYPEID, value);
    }

    /**
     * Gets the attribute value for SUPPORTING_DOC_TYPE_VALUE using the alias name SupportingDocTypeValue.
     * @return the SUPPORTING_DOC_TYPE_VALUE
     */
    public String getSupportingDocTypeValue() {
        return (String) getAttributeInternal(SUPPORTINGDOCTYPEVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPPORTING_DOC_TYPE_VALUE using the alias name SupportingDocTypeValue.
     * @param value value to set the SUPPORTING_DOC_TYPE_VALUE
     */
    public void setSupportingDocTypeValue(String value) {
        setAttributeInternal(SUPPORTINGDOCTYPEVALUE, value);
    }

    /**
     * Gets the attribute value for ATTACHMENT using the alias name Attachment.
     * @return the ATTACHMENT
     */
    public String getAttachment() {
        return (String) getAttributeInternal(ATTACHMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTACHMENT using the alias name Attachment.
     * @param value value to set the ATTACHMENT
     */
    public void setAttachment(String value) {
        setAttributeInternal(ATTACHMENT, value);
    }

    /**
     * Gets the attribute value for UPLOAD_DATE using the alias name UploadDate.
     * @return the UPLOAD_DATE
     */
    public Date getUploadDate() {
        return (Date) getAttributeInternal(UPLOADDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for UPLOAD_DATE using the alias name UploadDate.
     * @param value value to set the UPLOAD_DATE
     */
    public void setUploadDate(Date value) {
        setAttributeInternal(UPLOADDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UPDATED_DATE using the alias name UpdatedDate.
     * @return the UPDATED_DATE
     */
    public Date getUpdatedDate() {
        return (Date) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_DATE using the alias name UpdatedDate.
     * @param value value to set the UPDATED_DATE
     */
    public void setUpdatedDate(Date value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @return the UPDATED_BY
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @param value value to set the UPDATED_BY
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UPLOADED_BY using the alias name UploadedBy.
     * @return the UPLOADED_BY
     */
    public String getUploadedBy() {
        return (String) getAttributeInternal(UPLOADEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UPLOADED_BY using the alias name UploadedBy.
     * @param value value to set the UPLOADED_BY
     */
    public void setUploadedBy(String value) {
        setAttributeInternal(UPLOADEDBY, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> IcoDocAttachments.
     */
    public RowSet getIcoDocAttachments() {
        return (RowSet) getAttributeInternal(ICODOCATTACHMENTS);
    }
}

