package com.sgs.model.entity;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 17 23:56:24 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SgsCreateCreditMemosFImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CreditMemosId,
        CreditDate,
        PeoplesoftVoucherNum,
        PeoplesoftInvoiceNum,
        ReversalAmount,
        ReversalPercenatge,
        ReversalReasons,
        CompleteReversal,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CREDITMEMOSID = AttributesEnum.CreditMemosId.index();
    public static final int CREDITDATE = AttributesEnum.CreditDate.index();
    public static final int PEOPLESOFTVOUCHERNUM = AttributesEnum.PeoplesoftVoucherNum.index();
    public static final int PEOPLESOFTINVOICENUM = AttributesEnum.PeoplesoftInvoiceNum.index();
    public static final int REVERSALAMOUNT = AttributesEnum.ReversalAmount.index();
    public static final int REVERSALPERCENATGE = AttributesEnum.ReversalPercenatge.index();
    public static final int REVERSALREASONS = AttributesEnum.ReversalReasons.index();
    public static final int COMPLETEREVERSAL = AttributesEnum.CompleteReversal.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SgsCreateCreditMemosFImpl() {
    }

    /**
     * Gets the attribute value for CreditMemosId, using the alias name CreditMemosId.
     * @return the value of CreditMemosId
     */
    public Integer getCreditMemosId() {
        return (Integer) getAttributeInternal(CREDITMEMOSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreditMemosId.
     * @param value value to set the CreditMemosId
     */
    public void setCreditMemosId(Integer value) {
        setAttributeInternal(CREDITMEMOSID, value);
    }

    /**
     * Gets the attribute value for CreditDate, using the alias name CreditDate.
     * @return the value of CreditDate
     */
    public Date getCreditDate() {
        return (Date) getAttributeInternal(CREDITDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreditDate.
     * @param value value to set the CreditDate
     */
    public void setCreditDate(Date value) {
        setAttributeInternal(CREDITDATE, value);
    }

    /**
     * Gets the attribute value for PeoplesoftVoucherNum, using the alias name PeoplesoftVoucherNum.
     * @return the value of PeoplesoftVoucherNum
     */
    public String getPeoplesoftVoucherNum() {
        return (String) getAttributeInternal(PEOPLESOFTVOUCHERNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for PeoplesoftVoucherNum.
     * @param value value to set the PeoplesoftVoucherNum
     */
    public void setPeoplesoftVoucherNum(String value) {
        setAttributeInternal(PEOPLESOFTVOUCHERNUM, value);
    }

    /**
     * Gets the attribute value for PeoplesoftInvoiceNum, using the alias name PeoplesoftInvoiceNum.
     * @return the value of PeoplesoftInvoiceNum
     */
    public String getPeoplesoftInvoiceNum() {
        return (String) getAttributeInternal(PEOPLESOFTINVOICENUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for PeoplesoftInvoiceNum.
     * @param value value to set the PeoplesoftInvoiceNum
     */
    public void setPeoplesoftInvoiceNum(String value) {
        setAttributeInternal(PEOPLESOFTINVOICENUM, value);
    }

    /**
     * Gets the attribute value for ReversalAmount, using the alias name ReversalAmount.
     * @return the value of ReversalAmount
     */
    public BigDecimal getReversalAmount() {
        return (BigDecimal) getAttributeInternal(REVERSALAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReversalAmount.
     * @param value value to set the ReversalAmount
     */
    public void setReversalAmount(BigDecimal value) {
        setAttributeInternal(REVERSALAMOUNT, value);
    }

    /**
     * Gets the attribute value for ReversalPercenatge, using the alias name ReversalPercenatge.
     * @return the value of ReversalPercenatge
     */
    public String getReversalPercenatge() {
        return (String) getAttributeInternal(REVERSALPERCENATGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReversalPercenatge.
     * @param value value to set the ReversalPercenatge
     */
    public void setReversalPercenatge(String value) {
        setAttributeInternal(REVERSALPERCENATGE, value);
    }

    /**
     * Gets the attribute value for ReversalReasons, using the alias name ReversalReasons.
     * @return the value of ReversalReasons
     */
    public String getReversalReasons() {
        return (String) getAttributeInternal(REVERSALREASONS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReversalReasons.
     * @param value value to set the ReversalReasons
     */
    public void setReversalReasons(String value) {
        setAttributeInternal(REVERSALREASONS, value);
    }

    /**
     * Gets the attribute value for CompleteReversal, using the alias name CompleteReversal.
     * @return the value of CompleteReversal
     */
    public String getCompleteReversal() {
        return (String) getAttributeInternal(COMPLETEREVERSAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompleteReversal.
     * @param value value to set the CompleteReversal
     */
    public void setCompleteReversal(String value) {
        setAttributeInternal(COMPLETEREVERSAL, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Date getUpdatedDate() {
        return (Date) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedDate.
     * @param value value to set the UpdatedDate
     */
    public void setUpdatedDate(Date value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * @param creditMemosId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer creditMemosId) {
        return new Key(new Object[] { creditMemosId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.sgs.model.entity.SgsCreateCreditMemosF");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }
}

