package com.sgs.model.entity;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 17 23:58:08 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SgsCreateCreditMemosTImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CreditMemosId,
        CreditDate,
        AllocationId,
        FromBu,
        FromOu,
        FromDeptId,
        FromJobCode,
        ToBu,
        ToOu,
        ToDeptId,
        ToJobCode,
        OffsetGlAccountCr,
        ToGlAccountDr,
        TransactionCurrency,
        Amount,
        GstVatRate,
        GstVatAmount,
        InvoiceAmount,
        ReversalAmount,
        RevsersalGstVatAmount,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CREDITMEMOSID = AttributesEnum.CreditMemosId.index();
    public static final int CREDITDATE = AttributesEnum.CreditDate.index();
    public static final int ALLOCATIONID = AttributesEnum.AllocationId.index();
    public static final int FROMBU = AttributesEnum.FromBu.index();
    public static final int FROMOU = AttributesEnum.FromOu.index();
    public static final int FROMDEPTID = AttributesEnum.FromDeptId.index();
    public static final int FROMJOBCODE = AttributesEnum.FromJobCode.index();
    public static final int TOBU = AttributesEnum.ToBu.index();
    public static final int TOOU = AttributesEnum.ToOu.index();
    public static final int TODEPTID = AttributesEnum.ToDeptId.index();
    public static final int TOJOBCODE = AttributesEnum.ToJobCode.index();
    public static final int OFFSETGLACCOUNTCR = AttributesEnum.OffsetGlAccountCr.index();
    public static final int TOGLACCOUNTDR = AttributesEnum.ToGlAccountDr.index();
    public static final int TRANSACTIONCURRENCY = AttributesEnum.TransactionCurrency.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int GSTVATRATE = AttributesEnum.GstVatRate.index();
    public static final int GSTVATAMOUNT = AttributesEnum.GstVatAmount.index();
    public static final int INVOICEAMOUNT = AttributesEnum.InvoiceAmount.index();
    public static final int REVERSALAMOUNT = AttributesEnum.ReversalAmount.index();
    public static final int REVSERSALGSTVATAMOUNT = AttributesEnum.RevsersalGstVatAmount.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SgsCreateCreditMemosTImpl() {
    }

    /**
     * Gets the attribute value for CreditMemosId, using the alias name CreditMemosId.
     * @return the value of CreditMemosId
     */
    public Integer getCreditMemosId() {
        return (Integer) getAttributeInternal(CREDITMEMOSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreditMemosId.
     * @param value value to set the CreditMemosId
     */
    public void setCreditMemosId(Integer value) {
        setAttributeInternal(CREDITMEMOSID, value);
    }

    /**
     * Gets the attribute value for CreditDate, using the alias name CreditDate.
     * @return the value of CreditDate
     */
    public Date getCreditDate() {
        return (Date) getAttributeInternal(CREDITDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreditDate.
     * @param value value to set the CreditDate
     */
    public void setCreditDate(Date value) {
        setAttributeInternal(CREDITDATE, value);
    }

    /**
     * Gets the attribute value for AllocationId, using the alias name AllocationId.
     * @return the value of AllocationId
     */
    public String getAllocationId() {
        return (String) getAttributeInternal(ALLOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllocationId.
     * @param value value to set the AllocationId
     */
    public void setAllocationId(String value) {
        setAttributeInternal(ALLOCATIONID, value);
    }

    /**
     * Gets the attribute value for FromBu, using the alias name FromBu.
     * @return the value of FromBu
     */
    public String getFromBu() {
        return (String) getAttributeInternal(FROMBU);
    }

    /**
     * Sets <code>value</code> as the attribute value for FromBu.
     * @param value value to set the FromBu
     */
    public void setFromBu(String value) {
        setAttributeInternal(FROMBU, value);
    }

    /**
     * Gets the attribute value for FromOu, using the alias name FromOu.
     * @return the value of FromOu
     */
    public String getFromOu() {
        return (String) getAttributeInternal(FROMOU);
    }

    /**
     * Sets <code>value</code> as the attribute value for FromOu.
     * @param value value to set the FromOu
     */
    public void setFromOu(String value) {
        setAttributeInternal(FROMOU, value);
    }

    /**
     * Gets the attribute value for FromDeptId, using the alias name FromDeptId.
     * @return the value of FromDeptId
     */
    public String getFromDeptId() {
        return (String) getAttributeInternal(FROMDEPTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FromDeptId.
     * @param value value to set the FromDeptId
     */
    public void setFromDeptId(String value) {
        setAttributeInternal(FROMDEPTID, value);
    }

    /**
     * Gets the attribute value for FromJobCode, using the alias name FromJobCode.
     * @return the value of FromJobCode
     */
    public String getFromJobCode() {
        return (String) getAttributeInternal(FROMJOBCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FromJobCode.
     * @param value value to set the FromJobCode
     */
    public void setFromJobCode(String value) {
        setAttributeInternal(FROMJOBCODE, value);
    }

    /**
     * Gets the attribute value for ToBu, using the alias name ToBu.
     * @return the value of ToBu
     */
    public String getToBu() {
        return (String) getAttributeInternal(TOBU);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToBu.
     * @param value value to set the ToBu
     */
    public void setToBu(String value) {
        setAttributeInternal(TOBU, value);
    }

    /**
     * Gets the attribute value for ToOu, using the alias name ToOu.
     * @return the value of ToOu
     */
    public String getToOu() {
        return (String) getAttributeInternal(TOOU);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToOu.
     * @param value value to set the ToOu
     */
    public void setToOu(String value) {
        setAttributeInternal(TOOU, value);
    }

    /**
     * Gets the attribute value for ToDeptId, using the alias name ToDeptId.
     * @return the value of ToDeptId
     */
    public String getToDeptId() {
        return (String) getAttributeInternal(TODEPTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToDeptId.
     * @param value value to set the ToDeptId
     */
    public void setToDeptId(String value) {
        setAttributeInternal(TODEPTID, value);
    }

    /**
     * Gets the attribute value for ToJobCode, using the alias name ToJobCode.
     * @return the value of ToJobCode
     */
    public String getToJobCode() {
        return (String) getAttributeInternal(TOJOBCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToJobCode.
     * @param value value to set the ToJobCode
     */
    public void setToJobCode(String value) {
        setAttributeInternal(TOJOBCODE, value);
    }

    /**
     * Gets the attribute value for OffsetGlAccountCr, using the alias name OffsetGlAccountCr.
     * @return the value of OffsetGlAccountCr
     */
    public String getOffsetGlAccountCr() {
        return (String) getAttributeInternal(OFFSETGLACCOUNTCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for OffsetGlAccountCr.
     * @param value value to set the OffsetGlAccountCr
     */
    public void setOffsetGlAccountCr(String value) {
        setAttributeInternal(OFFSETGLACCOUNTCR, value);
    }

    /**
     * Gets the attribute value for ToGlAccountDr, using the alias name ToGlAccountDr.
     * @return the value of ToGlAccountDr
     */
    public String getToGlAccountDr() {
        return (String) getAttributeInternal(TOGLACCOUNTDR);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToGlAccountDr.
     * @param value value to set the ToGlAccountDr
     */
    public void setToGlAccountDr(String value) {
        setAttributeInternal(TOGLACCOUNTDR, value);
    }

    /**
     * Gets the attribute value for TransactionCurrency, using the alias name TransactionCurrency.
     * @return the value of TransactionCurrency
     */
    public String getTransactionCurrency() {
        return (String) getAttributeInternal(TRANSACTIONCURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransactionCurrency.
     * @param value value to set the TransactionCurrency
     */
    public void setTransactionCurrency(String value) {
        setAttributeInternal(TRANSACTIONCURRENCY, value);
    }

    /**
     * Gets the attribute value for Amount, using the alias name Amount.
     * @return the value of Amount
     */
    public BigDecimal getAmount() {
        return (BigDecimal) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Amount.
     * @param value value to set the Amount
     */
    public void setAmount(BigDecimal value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for GstVatRate, using the alias name GstVatRate.
     * @return the value of GstVatRate
     */
    public String getGstVatRate() {
        return (String) getAttributeInternal(GSTVATRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GstVatRate.
     * @param value value to set the GstVatRate
     */
    public void setGstVatRate(String value) {
        setAttributeInternal(GSTVATRATE, value);
    }

    /**
     * Gets the attribute value for GstVatAmount, using the alias name GstVatAmount.
     * @return the value of GstVatAmount
     */
    public BigDecimal getGstVatAmount() {
        return (BigDecimal) getAttributeInternal(GSTVATAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for GstVatAmount.
     * @param value value to set the GstVatAmount
     */
    public void setGstVatAmount(BigDecimal value) {
        setAttributeInternal(GSTVATAMOUNT, value);
    }

    /**
     * Gets the attribute value for InvoiceAmount, using the alias name InvoiceAmount.
     * @return the value of InvoiceAmount
     */
    public BigDecimal getInvoiceAmount() {
        return (BigDecimal) getAttributeInternal(INVOICEAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceAmount.
     * @param value value to set the InvoiceAmount
     */
    public void setInvoiceAmount(BigDecimal value) {
        setAttributeInternal(INVOICEAMOUNT, value);
    }

    /**
     * Gets the attribute value for ReversalAmount, using the alias name ReversalAmount.
     * @return the value of ReversalAmount
     */
    public BigDecimal getReversalAmount() {
        return (BigDecimal) getAttributeInternal(REVERSALAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReversalAmount.
     * @param value value to set the ReversalAmount
     */
    public void setReversalAmount(BigDecimal value) {
        setAttributeInternal(REVERSALAMOUNT, value);
    }

    /**
     * Gets the attribute value for RevsersalGstVatAmount, using the alias name RevsersalGstVatAmount.
     * @return the value of RevsersalGstVatAmount
     */
    public BigDecimal getRevsersalGstVatAmount() {
        return (BigDecimal) getAttributeInternal(REVSERSALGSTVATAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for RevsersalGstVatAmount.
     * @param value value to set the RevsersalGstVatAmount
     */
    public void setRevsersalGstVatAmount(BigDecimal value) {
        setAttributeInternal(REVSERSALGSTVATAMOUNT, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Date getUpdatedDate() {
        return (Date) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedDate.
     * @param value value to set the UpdatedDate
     */
    public void setUpdatedDate(Date value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * @param creditMemosId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer creditMemosId) {
        return new Key(new Object[] { creditMemosId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.sgs.model.entity.SgsCreateCreditMemosT");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }
}

