package com.sgs.model.entity;

import com.sgs.model.service.SGSAppModuleImpl;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 23 23:15:41 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SgsGstInquiryImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        GstNum,
        GstId,
        ServiceProvider,
        PlaceOfsupply,
        TypeOfsupply,
        TypeOfservice,
        Rcm,
        ExemptSupply,
        IdenticalGstReg,
        RateOfTax,
        HsnCode,
        ItemServiceCategory,
        IgstReceivable,
        CgstReceivable,
        SgstReceivable,
        IgstPayable,
        CgstPayable,
        SgstPayable,
        EffectiveFrom,
        EffectiveTo,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy,
        Recoverable,
        RATEOFTAX1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    private static final ADFLogger LOG = ADFLogger.createADFLogger(SgsAccPayInvoicesImpl.class);
    public static final int GSTNUM = AttributesEnum.GstNum.index();
    public static final int GSTID = AttributesEnum.GstId.index();
    public static final int SERVICEPROVIDER = AttributesEnum.ServiceProvider.index();
    public static final int PLACEOFSUPPLY = AttributesEnum.PlaceOfsupply.index();
    public static final int TYPEOFSUPPLY = AttributesEnum.TypeOfsupply.index();
    public static final int TYPEOFSERVICE = AttributesEnum.TypeOfservice.index();
    public static final int RCM = AttributesEnum.Rcm.index();
    public static final int EXEMPTSUPPLY = AttributesEnum.ExemptSupply.index();
    public static final int IDENTICALGSTREG = AttributesEnum.IdenticalGstReg.index();
    public static final int RATEOFTAX = AttributesEnum.RateOfTax.index();
    public static final int HSNCODE = AttributesEnum.HsnCode.index();
    public static final int ITEMSERVICECATEGORY = AttributesEnum.ItemServiceCategory.index();
    public static final int IGSTRECEIVABLE = AttributesEnum.IgstReceivable.index();
    public static final int CGSTRECEIVABLE = AttributesEnum.CgstReceivable.index();
    public static final int SGSTRECEIVABLE = AttributesEnum.SgstReceivable.index();
    public static final int IGSTPAYABLE = AttributesEnum.IgstPayable.index();
    public static final int CGSTPAYABLE = AttributesEnum.CgstPayable.index();
    public static final int SGSTPAYABLE = AttributesEnum.SgstPayable.index();
    public static final int EFFECTIVEFROM = AttributesEnum.EffectiveFrom.index();
    public static final int EFFECTIVETO = AttributesEnum.EffectiveTo.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int RECOVERABLE = AttributesEnum.Recoverable.index();
    public static final int RATEOFTAX1 = AttributesEnum.RATEOFTAX1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SgsGstInquiryImpl() {
    }

    /**
     * Gets the attribute value for GstNum, using the alias name GstNum.
     * @return the value of GstNum
     */
    public Integer getGstNum() {
        return (Integer) getAttributeInternal(GSTNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for GstNum.
     * @param value value to set the GstNum
     */
    public void setGstNum(Integer value) {
        setAttributeInternal(GSTNUM, value);
    }

    /**
     * Gets the attribute value for GstId, using the alias name GstId.
     * @return the value of GstId
     */
    public String getGstId() {
        return (String) getAttributeInternal(GSTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GstId.
     * @param value value to set the GstId
     */
    public void setGstId(String value) {
        setAttributeInternal(GSTID, value);
    }

    /**
     * Gets the attribute value for ServiceProvider, using the alias name ServiceProvider.
     * @return the value of ServiceProvider
     */
    public String getServiceProvider() {
        return (String) getAttributeInternal(SERVICEPROVIDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ServiceProvider.
     * @param value value to set the ServiceProvider
     */
    public void setServiceProvider(String value) {
        setAttributeInternal(SERVICEPROVIDER, value);
    }

    /**
     * Gets the attribute value for PlaceOfsupply, using the alias name PlaceOfsupply.
     * @return the value of PlaceOfsupply
     */
    public String getPlaceOfsupply() {
        return (String) getAttributeInternal(PLACEOFSUPPLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlaceOfsupply.
     * @param value value to set the PlaceOfsupply
     */
    public void setPlaceOfsupply(String value) {
        setAttributeInternal(PLACEOFSUPPLY, value);
    }

    /**
     * Gets the attribute value for TypeOfsupply, using the alias name TypeOfsupply.
     * @return the value of TypeOfsupply
     */
    public String getTypeOfsupply() {
        return (String) getAttributeInternal(TYPEOFSUPPLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TypeOfsupply.
     * @param value value to set the TypeOfsupply
     */
    public void setTypeOfsupply(String value) {
        setAttributeInternal(TYPEOFSUPPLY, value);
    }

    /**
     * Gets the attribute value for TypeOfservice, using the alias name TypeOfservice.
     * @return the value of TypeOfservice
     */
    public String getTypeOfservice() {
        return (String) getAttributeInternal(TYPEOFSERVICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TypeOfservice.
     * @param value value to set the TypeOfservice
     */
    public void setTypeOfservice(String value) {
        setAttributeInternal(TYPEOFSERVICE, value);
    }

    /**
     * Gets the attribute value for Rcm, using the alias name Rcm.
     * @return the value of Rcm
     */
    public String getRcm() {
        return (String) getAttributeInternal(RCM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rcm.
     * @param value value to set the Rcm
     */
    public void setRcm(String value) {
        setAttributeInternal(RCM, value);
    }

    /**
     * Gets the attribute value for ExemptSupply, using the alias name ExemptSupply.
     * @return the value of ExemptSupply
     */
    public String getExemptSupply() {
        return (String) getAttributeInternal(EXEMPTSUPPLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExemptSupply.
     * @param value value to set the ExemptSupply
     */
    public void setExemptSupply(String value) {
        setAttributeInternal(EXEMPTSUPPLY, value);
    }

    /**
     * Gets the attribute value for IdenticalGstReg, using the alias name IdenticalGstReg.
     * @return the value of IdenticalGstReg
     */
    public String getIdenticalGstReg() {
        return (String) getAttributeInternal(IDENTICALGSTREG);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdenticalGstReg.
     * @param value value to set the IdenticalGstReg
     */
    public void setIdenticalGstReg(String value) {
        setAttributeInternal(IDENTICALGSTREG, value);
    }

    /**
     * Gets the attribute value for RateOfTax, using the alias name RateOfTax.
     * @return the value of RateOfTax
     */
    public String getRateOfTax() {
        return (String) getAttributeInternal(RATEOFTAX);
    }

    /**
     * Sets <code>value</code> as the attribute value for RateOfTax.
     * @param value value to set the RateOfTax
     */
    public void setRateOfTax(String value) {
        setAttributeInternal(RATEOFTAX, value);
    }

    /**
     * Gets the attribute value for HsnCode, using the alias name HsnCode.
     * @return the value of HsnCode
     */
    public String getHsnCode() {
        return (String) getAttributeInternal(HSNCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for HsnCode.
     * @param value value to set the HsnCode
     */
    public void setHsnCode(String value) {
        setAttributeInternal(HSNCODE, value);
    }

    /**
     * Gets the attribute value for ItemServiceCategory, using the alias name ItemServiceCategory.
     * @return the value of ItemServiceCategory
     */
    public String getItemServiceCategory() {
        return (String) getAttributeInternal(ITEMSERVICECATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemServiceCategory.
     * @param value value to set the ItemServiceCategory
     */
    public void setItemServiceCategory(String value) {
        setAttributeInternal(ITEMSERVICECATEGORY, value);
    }

    /**
     * Gets the attribute value for IgstReceivable, using the alias name IgstReceivable.
     * @return the value of IgstReceivable
     */
    public String getIgstReceivable() {
        return (String) getAttributeInternal(IGSTRECEIVABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IgstReceivable.
     * @param value value to set the IgstReceivable
     */
    public void setIgstReceivable(String value) {
        setAttributeInternal(IGSTRECEIVABLE, value);
    }

    /**
     * Gets the attribute value for CgstReceivable, using the alias name CgstReceivable.
     * @return the value of CgstReceivable
     */
    public String getCgstReceivable() {
        return (String) getAttributeInternal(CGSTRECEIVABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CgstReceivable.
     * @param value value to set the CgstReceivable
     */
    public void setCgstReceivable(String value) {
        setAttributeInternal(CGSTRECEIVABLE, value);
    }

    /**
     * Gets the attribute value for SgstReceivable, using the alias name SgstReceivable.
     * @return the value of SgstReceivable
     */
    public String getSgstReceivable() {
        return (String) getAttributeInternal(SGSTRECEIVABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SgstReceivable.
     * @param value value to set the SgstReceivable
     */
    public void setSgstReceivable(String value) {
        setAttributeInternal(SGSTRECEIVABLE, value);
    }

    /**
     * Gets the attribute value for IgstPayable, using the alias name IgstPayable.
     * @return the value of IgstPayable
     */
    public String getIgstPayable() {
        return (String) getAttributeInternal(IGSTPAYABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IgstPayable.
     * @param value value to set the IgstPayable
     */
    public void setIgstPayable(String value) {
        setAttributeInternal(IGSTPAYABLE, value);
    }

    /**
     * Gets the attribute value for CgstPayable, using the alias name CgstPayable.
     * @return the value of CgstPayable
     */
    public String getCgstPayable() {
        return (String) getAttributeInternal(CGSTPAYABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CgstPayable.
     * @param value value to set the CgstPayable
     */
    public void setCgstPayable(String value) {
        setAttributeInternal(CGSTPAYABLE, value);
    }

    /**
     * Gets the attribute value for SgstPayable, using the alias name SgstPayable.
     * @return the value of SgstPayable
     */
    public String getSgstPayable() {
        return (String) getAttributeInternal(SGSTPAYABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SgstPayable.
     * @param value value to set the SgstPayable
     */
    public void setSgstPayable(String value) {
        setAttributeInternal(SGSTPAYABLE, value);
    }

    /**
     * Gets the attribute value for EffectiveFrom, using the alias name EffectiveFrom.
     * @return the value of EffectiveFrom
     */
    public Date getEffectiveFrom() {
        return (Date) getAttributeInternal(EFFECTIVEFROM);
    }

    /**
     * Sets <code>value</code> as the attribute value for EffectiveFrom.
     * @param value value to set the EffectiveFrom
     */
    public void setEffectiveFrom(Date value) {
        setAttributeInternal(EFFECTIVEFROM, value);
    }

    /**
     * Gets the attribute value for EffectiveTo, using the alias name EffectiveTo.
     * @return the value of EffectiveTo
     */
    public Date getEffectiveTo() {
        return (Date) getAttributeInternal(EFFECTIVETO);
    }

    /**
     * Sets <code>value</code> as the attribute value for EffectiveTo.
     * @param value value to set the EffectiveTo
     */
    public void setEffectiveTo(Date value) {
        setAttributeInternal(EFFECTIVETO, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Date getUpdatedDate() {
        return (Date) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedDate.
     * @param value value to set the UpdatedDate
     */
    public void setUpdatedDate(Date value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for Recoverable, using the alias name Recoverable.
     * @return the value of Recoverable
     */
    public String getRecoverable() {
        return (String) getAttributeInternal(RECOVERABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Recoverable.
     * @param value value to set the Recoverable
     */
    public void setRecoverable(String value) {
        setAttributeInternal(RECOVERABLE, value);
    }

    /**
     * Gets the attribute value for RATEOFTAX1, using the alias name RATEOFTAX1.
     * @return the value of RATEOFTAX1
     */
    public BigDecimal getRATEOFTAX1() {
        return (BigDecimal) getAttributeInternal(RATEOFTAX1);
    }

    /**
     * Sets <code>value</code> as the attribute value for RATEOFTAX1.
     * @param value value to set the RATEOFTAX1
     */
    public void setRATEOFTAX1(BigDecimal value) {
        setAttributeInternal(RATEOFTAX1, value);
    }

    /**
     * @param gstNum key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer gstNum) {
        return new Key(new Object[] { gstNum });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.sgs.model.entity.SgsGstInquiry");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        try {
            SGSAppModuleImpl am = new SGSAppModuleImpl();
            setGstNum(am.getDBSequence("SGS_GST_INQUIRY_SEQ"));
        } catch (Exception e) {
            LOG.severe(e);
        }
    }
}

