package com.sgs.model.entity;

import com.sgs.model.service.SGSAppModuleImpl;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 10 20:11:15 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SgsOtherReceivables1Impl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        OrId,
        Period,
        VoucherId,
        FromBusinessUnit,
        FromOperatingUnit,
        ToBusinessUnit,
        ToOperatingUnit,
        FromJobCode,
        FromDepartmentId,
        ToJobCode,
        ToDepartmentId,
        CrGlAccount,
        DrGlAccount,
        BaseCurrency,
        TransactionCurrency,
        Amount,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    private static final ADFLogger LOG = ADFLogger.createADFLogger(SgsOtherReceivables1Impl.class);
    public static final int ORID = AttributesEnum.OrId.index();
    public static final int PERIOD = AttributesEnum.Period.index();
    public static final int VOUCHERID = AttributesEnum.VoucherId.index();
    public static final int FROMBUSINESSUNIT = AttributesEnum.FromBusinessUnit.index();
    public static final int FROMOPERATINGUNIT = AttributesEnum.FromOperatingUnit.index();
    public static final int TOBUSINESSUNIT = AttributesEnum.ToBusinessUnit.index();
    public static final int TOOPERATINGUNIT = AttributesEnum.ToOperatingUnit.index();
    public static final int FROMJOBCODE = AttributesEnum.FromJobCode.index();
    public static final int FROMDEPARTMENTID = AttributesEnum.FromDepartmentId.index();
    public static final int TOJOBCODE = AttributesEnum.ToJobCode.index();
    public static final int TODEPARTMENTID = AttributesEnum.ToDepartmentId.index();
    public static final int CRGLACCOUNT = AttributesEnum.CrGlAccount.index();
    public static final int DRGLACCOUNT = AttributesEnum.DrGlAccount.index();
    public static final int BASECURRENCY = AttributesEnum.BaseCurrency.index();
    public static final int TRANSACTIONCURRENCY = AttributesEnum.TransactionCurrency.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SgsOtherReceivables1Impl() {
    }

    /**
     * Gets the attribute value for OrId, using the alias name OrId.
     * @return the value of OrId
     */
    public Integer getOrId() {
        return (Integer) getAttributeInternal(ORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrId.
     * @param value value to set the OrId
     */
    public void setOrId(Integer value) {
        setAttributeInternal(ORID, value);
    }

    /**
     * Gets the attribute value for Period, using the alias name Period.
     * @return the value of Period
     */
    public String getPeriod() {
        return (String) getAttributeInternal(PERIOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for Period.
     * @param value value to set the Period
     */
    public void setPeriod(String value) {
        setAttributeInternal(PERIOD, value);
    }

    /**
     * Gets the attribute value for VoucherId, using the alias name VoucherId.
     * @return the value of VoucherId
     */
    public String getVoucherId() {
        return (String) getAttributeInternal(VOUCHERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for VoucherId.
     * @param value value to set the VoucherId
     */
    public void setVoucherId(String value) {
        setAttributeInternal(VOUCHERID, value);
    }

    /**
     * Gets the attribute value for FromBusinessUnit, using the alias name FromBusinessUnit.
     * @return the value of FromBusinessUnit
     */
    public String getFromBusinessUnit() {
        return (String) getAttributeInternal(FROMBUSINESSUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for FromBusinessUnit.
     * @param value value to set the FromBusinessUnit
     */
    public void setFromBusinessUnit(String value) {
        setAttributeInternal(FROMBUSINESSUNIT, value);
    }

    /**
     * Gets the attribute value for FromOperatingUnit, using the alias name FromOperatingUnit.
     * @return the value of FromOperatingUnit
     */
    public String getFromOperatingUnit() {
        return (String) getAttributeInternal(FROMOPERATINGUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for FromOperatingUnit.
     * @param value value to set the FromOperatingUnit
     */
    public void setFromOperatingUnit(String value) {
        setAttributeInternal(FROMOPERATINGUNIT, value);
    }

    /**
     * Gets the attribute value for ToBusinessUnit, using the alias name ToBusinessUnit.
     * @return the value of ToBusinessUnit
     */
    public String getToBusinessUnit() {
        return (String) getAttributeInternal(TOBUSINESSUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToBusinessUnit.
     * @param value value to set the ToBusinessUnit
     */
    public void setToBusinessUnit(String value) {
        setAttributeInternal(TOBUSINESSUNIT, value);
    }

    /**
     * Gets the attribute value for ToOperatingUnit, using the alias name ToOperatingUnit.
     * @return the value of ToOperatingUnit
     */
    public String getToOperatingUnit() {
        return (String) getAttributeInternal(TOOPERATINGUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToOperatingUnit.
     * @param value value to set the ToOperatingUnit
     */
    public void setToOperatingUnit(String value) {
        setAttributeInternal(TOOPERATINGUNIT, value);
    }

    /**
     * Gets the attribute value for FromJobCode, using the alias name FromJobCode.
     * @return the value of FromJobCode
     */
    public String getFromJobCode() {
        return (String) getAttributeInternal(FROMJOBCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FromJobCode.
     * @param value value to set the FromJobCode
     */
    public void setFromJobCode(String value) {
        setAttributeInternal(FROMJOBCODE, value);
    }

    /**
     * Gets the attribute value for FromDepartmentId, using the alias name FromDepartmentId.
     * @return the value of FromDepartmentId
     */
    public String getFromDepartmentId() {
        return (String) getAttributeInternal(FROMDEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FromDepartmentId.
     * @param value value to set the FromDepartmentId
     */
    public void setFromDepartmentId(String value) {
        setAttributeInternal(FROMDEPARTMENTID, value);
    }

    /**
     * Gets the attribute value for ToJobCode, using the alias name ToJobCode.
     * @return the value of ToJobCode
     */
    public String getToJobCode() {
        return (String) getAttributeInternal(TOJOBCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToJobCode.
     * @param value value to set the ToJobCode
     */
    public void setToJobCode(String value) {
        setAttributeInternal(TOJOBCODE, value);
    }

    /**
     * Gets the attribute value for ToDepartmentId, using the alias name ToDepartmentId.
     * @return the value of ToDepartmentId
     */
    public String getToDepartmentId() {
        return (String) getAttributeInternal(TODEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToDepartmentId.
     * @param value value to set the ToDepartmentId
     */
    public void setToDepartmentId(String value) {
        setAttributeInternal(TODEPARTMENTID, value);
    }

    /**
     * Gets the attribute value for CrGlAccount, using the alias name CrGlAccount.
     * @return the value of CrGlAccount
     */
    public String getCrGlAccount() {
        return (String) getAttributeInternal(CRGLACCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CrGlAccount.
     * @param value value to set the CrGlAccount
     */
    public void setCrGlAccount(String value) {
        setAttributeInternal(CRGLACCOUNT, value);
    }

    /**
     * Gets the attribute value for DrGlAccount, using the alias name DrGlAccount.
     * @return the value of DrGlAccount
     */
    public String getDrGlAccount() {
        return (String) getAttributeInternal(DRGLACCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DrGlAccount.
     * @param value value to set the DrGlAccount
     */
    public void setDrGlAccount(String value) {
        setAttributeInternal(DRGLACCOUNT, value);
    }

    /**
     * Gets the attribute value for BaseCurrency, using the alias name BaseCurrency.
     * @return the value of BaseCurrency
     */
    public String getBaseCurrency() {
        return (String) getAttributeInternal(BASECURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for BaseCurrency.
     * @param value value to set the BaseCurrency
     */
    public void setBaseCurrency(String value) {
        setAttributeInternal(BASECURRENCY, value);
    }

    /**
     * Gets the attribute value for TransactionCurrency, using the alias name TransactionCurrency.
     * @return the value of TransactionCurrency
     */
    public String getTransactionCurrency() {
        return (String) getAttributeInternal(TRANSACTIONCURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransactionCurrency.
     * @param value value to set the TransactionCurrency
     */
    public void setTransactionCurrency(String value) {
        setAttributeInternal(TRANSACTIONCURRENCY, value);
    }

    /**
     * Gets the attribute value for Amount, using the alias name Amount.
     * @return the value of Amount
     */
    public BigDecimal getAmount() {
        return (BigDecimal) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Amount.
     * @param value value to set the Amount
     */
    public void setAmount(BigDecimal value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Date getUpdatedDate() {
        return (Date) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedDate.
     * @param value value to set the UpdatedDate
     */
    public void setUpdatedDate(Date value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * @param orId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer orId) {
        return new Key(new Object[] { orId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.sgs.model.entity.SgsOtherReceivables1");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        try {
            SGSAppModuleImpl am = new SGSAppModuleImpl();
            setOrId(am.getDBSequence("SGS_OTHER_RECEIVABLES1_SEQ"));
        } catch (Exception e) {
            LOG.severe(e);
        }
    }
}

